name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main  # 适应你的主分支名称

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
        
    - name: Build Hugo site
      run: hugo --minify
      
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.ACCESS_TOKEN }}
        
    - name: Deploy Hugo site to Tencent Cloud
      run: |
        scp -r ./public/* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.TARGET }}
