# deploy.yml
name: Deploy Hugo site with rsync
 
on:
  push:
    branches:
      - main  # Replace with your default branch name
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  # Checkout the repo
        uses: actions/checkout@v2
 
      - name: Install Hugo  # Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
 
      - name: Build  # Build the site
        run: hugo --minify
 
      - name: Deploy  # Deploy the site
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}  # Replace with your server's target directory
